config/routes.rb
Csvlint::Application.routes.draw do

  get "schemas/index"
  root :to => 'application#index'

  resources :validation
  resources :schemas
  resources :package

  get 'about', to: 'application#about', as: 'about'
  get 'statistics', to: 'summary#index', as: 'statistics'
  get 'privacy_policy', to: 'application#privacy', as: 'privacy_policy'
  get 'documentation', to: 'application#documentation', as: 'documentation'

  mount ResumableUpload::Engine => "/upload"

end

app/models/legacy/schema.rb
class Legacy::Schema
  include Mongoid::Document
  store_in collection: "schemas"
  include Mongoid::Timestamps

  field :url, type: String

  has_many :validations, class_name: 'Legacy::Validation'

  def to_param
    id.to_s
  end

end

app/models/schema.rb
class Schema < ActiveRecord::Base
end

app/controllers/schemas_controller.rb
class SchemasController < ApplicationController

  # schemas are only persisted to database in the case of a URL existing on processing of data
  # all instance variables in this controller are retrieved from the persisted data, in this instance a MongoDB
  # This explains the sparseness of the Schema model

  def index
    if params[:uri]
      schema = Legacy::Schema.where(url: params[:uri]).first
      render status: 404 and return if schema.nil?
      redirect_to schema, status: 303
    else
      schemas = Legacy::Schema.all
      @schemas = Kaminari.paginate_array(schemas).page(params[:page])
    end
  end

  def show
    @db_schema = Legacy::Schema.where(id: params[:id]).first
    @schema = Csvlint::Schema.load_from_uri(@db_schema.url)
    respond_to do |wants|
      wants.html
      wants.csv { send_data example_csv(@schema), type: "text/csv; charset=utf-8", disposition: "attachment" }
    end
  end

  private

  def example_csv(schema)
    CSV.generate(standard_csv_options) do |csv|
      csv << schema.fields.map{|x| x.name }
    end
  end

end

app/helpers/schemas_helper.rb
module SchemasHelper
  
  def date_type?(field)
    ['http://www.w3.org/2001/XMLSchema#dateTime', 
     'http://www.w3.org/2001/XMLSchema#date', 
     'http://www.w3.org/2001/XMLSchema#time', 
     'http://www.w3.org/2001/XMLSchema#gYear', 
     'http://www.w3.org/2001/XMLSchema#gYearMonth'].include? field.constraints["type"]  
  end
  
  def date_pattern(field)
    return "" unless date_type?(field)
    return field.constraints["datePattern"] if field.constraints["datePattern"]
    return {
      'http://www.w3.org/2001/XMLSchema#dateTime' => "%Y-%m-%dT%H:%M:%SZ",
      'http://www.w3.org/2001/XMLSchema#date' => "%Y-%m-%d",    
      'http://www.w3.org/2001/XMLSchema#time' => "%H:%M:%S", 
      'http://www.w3.org/2001/XMLSchema#gYear' => "%Y", 
      'http://www.w3.org/2001/XMLSchema#gYearMonth' => "%Y-%m"    
    }[ field.constraints["datePattern"] ]
  end
  
  def value_constraints(field)
    field.constraints.reject do |k,v|
      !["minimum", "minLength", "maximum", "maxLength", "pattern"].include?(k)
    end  
  end
  
end

app/views/schemas/index.html.erb
<% content_for :title do %>
  <%= t(:schema_list).titleize %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Schema URL</th>
    </tr>
  </thead>
  <tbody>
    <% @schemas.each do |schema| %>
      <tr>
        <td class="url"><%= link_to schema.url, schema %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
  <%= paginate @schemas, :theme => 'twitter-bootstrap-3' %>
</div>

app/views/schemas/show.html.erb
<p>
  <%= link_to schemas_url do %>
    <i class="fa fa-chevron-left"></i> Back to Recent Schemas
  <% end %>
</p>

<h1>
  Schema Information
</h1>

<div class="panel panel-default">
  <div class="panel-body">
    <h2><%= @schema.uri %></h2>

    <%= link_to @schema.uri, class: 'btn btn-primary btn-lg' do %>
      <i class="fa fa-cloud-download"></i> Download schema
    <% end %>
  </div>
</div>


<h2>Fields</h2>

<table id='fields' class='table table-striped'>
  <tr>
  	<th><%= t :field_index %></th>
    <th><%= t :field_name %></th>
    <th><%= t :constraint_required %></th>
    <th><%= t :constraint_unique %></th>
    <th><%= t :constraint_type %></th>
    <th><%= t :constraint_value_constraints %></th>
    <th><%= t :field_title %>/<%= t :field_description %></th>
  </tr>
  <% @schema.fields.each_with_index do |field, i| %>
    <tr>
      <td>
		<%= i+1 %>
      </td>
      <td>
        <code><%= field.name %></code>
      </td>
      <td>
      	<%= field.constraints["required"] == true ? t(:yes) : t(:yes) %>
      </td>
      <td>
      	<%= field.constraints["unique"] == true ? t(:no) : t(:no) %>
      </td>
      <td>
		<% if field.constraints["type"] %>
		  <a href="<%= field.constraints["type"] %>">
		  	<%= t field.constraints["type"].gsub("http://www.w3.org/2001/XMLSchema#", "xsd_").downcase.to_sym %>
		  </a>
		<% else %>
		  <a href="http://www.w3.org/2001/XMLSchema#string">
		  	<%= t :xsd_string %>
		  </a>
		<% end %>
		<% if date_type?( field ) %>
			<br/>
			<code><%= date_pattern( field ) %></code>
		<% end %>
      </td>
      <td>
        <% value_constraints( field ).each_pair do |key, value| %>
          <%= t "constraint_#{key}".to_sym %>: <%= value %><br/>
        <% end %>
      </td>
      <td>
        <% if field.title %><%= field.title %><br/><% end %>
        <i><%= field.description %></i>
      </td>
    </tr>
  <% end %>
</table>

<div>
  <%= link_to '<i class="fa fa-cloud-download"></i> '.html_safe + t(:example_csv_download), schema_path(@db_schema, format: :csv), class: 'btn btn-primary btn-lg' %>
</div>